### ISSUE TITLE
ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by senarclens** [tsung-ju/eleventy-plugin-mathjax#2]
My eleventy based page is generated via gitlab runners based on node:lts-alpine. Since a recent update, this uses npm version 8.1.0. `npm install`  fails with

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: htl-bulme@0.0.2
npm ERR! Found: @11ty/eleventy@0.12.1
npm ERR! node_modules/@11ty/eleventy
npm ERR!   dev @11ty/eleventy@"^0.12.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @11ty/eleventy@"^0.3.3" from eleventy-plugin-mathjax@2.0.2
npm ERR! node_modules/eleventy-plugin-mathjax
npm ERR!   dev eleventy-plugin-mathjax@"^2.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.
```

I could reproduce this by running clone `git@gitlab.com:senarclens/htl-bulme.git` and then running `npm install` with npm versions 8.1.0 and 8.1.2.

The issue here is the peer dependency defined in https://github.com/tsung-ju/eleventy-plugin-mathjax/blame/main/package.json#L27
While I'm not sure why the dev dependency `@11ty/eleventy@"^0.12.1"` does not satisfy `peer @11ty/eleventy@"^0.3.3"` and why the latter cannot be resolved, there seems to be an eleventy specific resolution to this problem suggested here: https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/62 with relevant code changes available here: https://github.com/11ty/eleventy-plugin-syntaxhighlight/commit/40d1bc65ccfb35a6b07f3a782ff6305f2fc08913

A possible workaround is to run `npm install --legacy-peer-deps` for now.

I suggest using the same resolution as proposed for the syntaxhighlight plugin, but any other hint on how to resolve this is welcome. Thanks.

**Comment by tsung-ju** [comment]
Thanks for the information! I'll look into it.
