### ISSUE TITLE
Some subscripts are not formatted

### ISSUE THREAD

**Issue by SilvestriStefano** [tsung-ju/eleventy-plugin-mathjax#4]
Hello,
I am encountering an issue when using symbols or braces for subscripts.

## Example
In a `.md` file I write 
```markdown
## Main Project
My research project concerns the sets pictured below. 
$$x+y=0$$

soeme thoiaex adad $ \mathbb{D}_9 $ caslsalnlca. $ \mathcal{M} \subset \mathfrak{C} $.
saubiabascb  kscabcacs asjk jkba idhbkacicakscbaluc ab lasjcajclqc l9 clajmc li jascasij kl  $\mathcal{E}^-\subset\mathcal{F}^{5-4}$

lks;i; d'pj 'sdj dsc;M :S,;sdc'al ' qci $\mathcal{M}_k\subset\mathcal{M}^{f+gte}$ asnasochjanoa ocn9dh akcnapcn achq90 q qpk qdkqph q 9d  pk p  hdo mpj aicnsalc anxp  askan some good word $x-$
``` 
is rendered fine
![image](https://user-images.githubusercontent.com/18087952/216775073-19906582-3bc3-48e2-9092-d8398002e903.png)

however if I change the last equation from `$x-$` to `$x_-$` or `$x_{-}$` or `$x_{67}$` or `$x_{somewords}$` , things go awry
![image](https://user-images.githubusercontent.com/18087952/216775303-c9197bd8-8196-4c44-bde8-2a5af1995747.png)

![image](https://user-images.githubusercontent.com/18087952/216775970-0fb28ead-4ce0-4d0e-b5d6-9e990c2e7288.png)

![image](https://user-images.githubusercontent.com/18087952/216775942-8d0bf4c4-060a-49ac-adbc-d5c311f0ee78.png)

![image](https://user-images.githubusercontent.com/18087952/216775347-5772053a-2669-44b8-a825-b9b5a305becf.png)

__Note that this does not happen with the superscript.__

__Note also that this is happens both on Firefox and with Chrome.__

## Configuration
Here is my 11ty configuration.
```js
module.exports = function (eleventyConfig) {
  // Passthrough
    //fonts
  eleventyConfig.addPassthroughCopy("./src/assets/fonts/");
  eleventyConfig.addWatchTarget("./src/assets/fonts/");
    //css
  eleventyConfig.addPassthroughCopy("./src/assets/css/");
  eleventyConfig.addWatchTarget("./src/assets/css/");
    //js
  eleventyConfig.addPassthroughCopy("./src/assets/js/");
  eleventyConfig.addWatchTarget("./src/assets/js/");  
    //img
  eleventyConfig.addPassthroughCopy("./src/assets/img/");
  eleventyConfig.addWatchTarget("./src/assets/img/");
  
  // Plugin
    // navigation
  eleventyConfig.addPlugin( require("@11ty/eleventy-navigation") );
  eleventyConfig.addPlugin( require("eleventy-plugin-mathjax",{
    displayMath: [
      ["$$", "$$"]
    ]
  }) );
    
  //Shortcodes
  eleventyConfig.addShortcode("year", () => `${new Date().getFullYear()}`);
  eleventyConfig.addShortcode("navlist", require("./src/_includes/shortcodes/navlist.js"));
    
  return {
    dir: {
      input: "src",
      output: "public",
      },
    };
};
```

I am using Ubuntu 20.04.5 LTS but I doubt this is relevant. 

Any suggestion on how to resolve this issue?
Thank you

**Comment by tsung-ju** [comment]
It's likely because the Markdown engine turned the characters between the two `_` into italics.
Adding a `\` before the `_` could prevent that from happening.

See also [this markdown-it plugin](https://github.com/tani/markdown-it-mathjax3),
which can be used with eleventy's custom markdown-it engine feature,
and doesn't have these escaping issues.

**Comment by SilvestriStefano** [comment]
Hello,
I have tried adding the `\` but it still does not work. I'll check with markdown-it. 
Thank you!
